export const PRODUCTS_LOAD = "PRODUCTS_LOAD";
export const GET_CATEGORY_NAME = "GET_CATEGORY_NAME";
export const ADD_ITEMS_CART = "ADD_ITEMS_CART";
export const REMOVE_ITEMS_CART = "REMOVE_ITEMS_CART";
export const LOADER_DISPLAY_ON = "LOADER_DISPLAY_ON";
export const LOADER_DISPLAY_OFF = "LOADER_DISPLAY_OFF";
